# v1.17.0生成的apiserver工程加载healthz路径报错

参考文章

1. [Duplicate install health checkers for etcd](https://github.com/kubernetes-sigs/apiserver-builder-alpha/issues/504)

[apiserver-builder-alpha release: v1.17.0](https://github.com/kubernetes-sigs/apiserver-builder-alpha/releases/tag/v1.17.0)

按照我摸索到的方法使用 apiserver-builder 创建了一个工程, 使用如下命令启动

```
go run main.go --secure-port 1443 --kubeconfig /etc/kubernetes/admin.conf --etcd-servers https://172.16.91.10:2379 --etcd-cafile /etc/kubernetes/pki/etcd/ca.crt --etcd-certfile /etc/kubernetes/pki/etcd/server.crt --etcd-keyfile /etc/kubernetes/pki/etcd/server.key -v 5
```

却有如下报错.

```
I1015 22:11:14.282792   13889 healthz.go:123] Installing health checkers for (/healthz): "ping","log","etcd","etcd","poststarthook/generic-apiserver-start-informers","poststarthook/aggregated-resource-informer"
E1015 22:11:14.283023   13889 pathrecorder.go:107] registered "/healthz/etcd" from goroutine 1 [running]:
runtime/debug.Stack(0x1ae3a00, 0xc0000e1830, 0xc00029a560)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc0002b68c0, 0xc00029a560, 0xd)
	/usr/local/gopath/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/mux/pathrecorder.go:109 +0x86
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).Handle(0xc0002b68c0, 0xc00029a560, 0xd, 0x26e9540, 0xc0008c14a0)
	/usr/local/gopath/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/mux/pathrecorder.go:173 +0x86
k8s.io/apiserver/pkg/server/healthz.InstallPathHandler(0x26e6b60, 0xc0002b68c0, 0x1d7db76, 0x8, 0xc0000e6d00, 0x6, 0x8)
	/usr/local/gopath/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/healthz/healthz.go:127 +0x39e
k8s.io/apiserver/pkg/server/healthz.InstallHandler(...)
	/usr/local/gopath/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/healthz/healthz.go:93
k8s.io/apiserver/pkg/server.(*GenericAPIServer).installHealthz(0xc0002d3c20)
	/usr/local/gopath/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/healthz.go:96 +0xc6
k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc0002d3c20, 0xc000114210)
	/usr/local/gopath/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/genericapiserver.go:292 +0x5c
sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.(*ServerOptions).RunServer(0xc00021a1e0, 0xc0000b4480, 0x1d7868c, 0x3, 0x1d780c1, 0x2, 0x0, 0x0, 0x0, 0x1d7960c, ...)
	/usr/local/gopath/pkg/mod/sigs.k8s.io/apiserver-builder-alpha@v1.17.0/pkg/cmd/server/start.go:416 +0x483
sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.NewCommandStartServer.func1(0xc00038a000, 0xc000274000, 0x0, 0xe, 0x0, 0x0)
	/usr/local/gopath/pkg/mod/sigs.k8s.io/apiserver-builder-alpha@v1.17.0/pkg/cmd/server/start.go:185 +0xf3
github.com/spf13/cobra.(*Command).execute(0xc00038a000, 0xc00004e100, 0xe, 0xe, 0xc00038a000, 0xc00004e100)
	/usr/local/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc00038a000, 0xc0001e6100, 0x26e7900, 0xc000010018)
	/usr/local/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/usr/local/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
sigs.k8s.io/apiserver-builder-alpha/pkg/cmd/server.StartApiServerWithOptions(0xc0005aff08, 0xc0000108f8, 0xc000314b40)
	/usr/local/gopath/pkg/mod/sigs.k8s.io/apiserver-builder-alpha@v1.17.0/pkg/cmd/server/start.go:119 +0x2cd
main.main()
	/home/apiserver-builder-project/cmd/apiserver/main.go:25 +0x10d
```

除了上面的`/healthz/etcd`, 还有`/livez/etcd`, `/readyz/etcd`, 内容都比较像.

但是工程仍然能够正常运行, 我还尝试着访问了一下

```console
$ curl -k https://localhost:1443/readyz/etcd
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/readyz/etcd\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
}
```

好像没什么问题, 这个uri明明注册成功了.

但是报错是中的日志级别为`Error`, 不是`Warning`, 不好就这么忽略了, 于是我按照报错到源码中看了看.

在`/usr/local/gopath/pkg/mod/k8s.io/apiserver@v0.17.3/pkg/server/mux/pathrecorder.go:109`处内容如下

```go
func (m *PathRecorderMux) trackCallers(path string) {
    if existingStack, ok := m.pathStacks[path]; ok {
        // 就是这一行
		utilruntime.HandleError(fmt.Errorf("registered %q from %v", path, existingStack))
	}
	m.pathStacks[path] = string(debug.Stack())
}
```

看起来像是在注册路由的时候已经存在了相同的地址, 我试着在官方 issues 中搜索了下`/healthz/etcd`, 还真的找到了相关的问题, 见参考文章1. 提问者发起了一个 issue 并被合并到了主分支, 我对比了一个 1.17.0 与ta提交 pr 的时间, 确认了这个问题, 改用 1.18.0 后正常.
